 return {}
-- vim.cmd([[ let g:neo_tree_remove_legacy_commands = 1 ]])

-- return {
--   "nvim-neo-tree/neo-tree.nvim",
--   version = "*",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
--     "MunifTanjim/nui.nvim",
--   },
--   config = function ()
--     require('neo-tree').setup {
--       autochdir = true,
--       update_cwd = true,
--       follow_current_file = true,
--       update_to_buf_dir = {
--         enable = true,
--         auto_open = true,
--       },
--       update_focused_file = {
--         enable = true,
--         update_cwd = true,
--         ignore_list = {},
--       },
--     }
--   end,
--   keys = {
--     {
--       "<Leader>e",
--       function()
--         require("neo-tree.command").execute({ toggle = true })
--       end,
--     }, -- change or remove this line if relevant.
--   },
-- }
